Repository Ruletk/WarehouseSystem, pull requests merged in 2025-01, with the labels that each got.

#4 Update README and add LICENSE file
  LICENSE
  README.md
Labels: documentation

#5 Improved routes by separating handlers, added DI, added tests for auth routing.
  apps/auth-e2e/src/auth/auth.spec.ts
  apps/auth-e2e/src/support/test-setup.ts
  apps/auth/src/routes/authHandlers.test.ts
  apps/auth/src/routes/authHandlers.ts
  apps/auth/src/routes/authRoute.ts
Labels: enhancement

#7 Shared library for logging
  .gitignore
  docker-compose.yaml
  nx.json
  package-lock.json
  package.json
  services/elk/logstash.conf
  services/filebeat/Dockerfile
  services/filebeat/filebeat.yml
  shared/README.md
  shared/eslint.config.cjs
  shared/jest.config.ts
  shared/package.json
  shared/project.json
  shared/src/index.ts
  shared/src/lib/logging.spec.ts
  shared/src/lib/logging.ts
  shared/tsconfig.json
  shared/tsconfig.lib.json
  shared/tsconfig.spec.json
  tsconfig.base.json
Labels: enhancement

#8 Models and repositories
  apps/stock/src/models/item.ts
  apps/stock/src/repositories/itemRepository.ts
  package-lock.json
  package.json
Labels: enhancement

#12 WAR-108
  shared/logging/README.md
  shared/logging/eslint.config.cjs
  shared/logging/jest.config.ts
  shared/logging/package.json
  shared/logging/project.json
  shared/logging/src/index.ts
  shared/logging/src/lib/logging.spec.ts
  shared/logging/src/lib/logging.ts
  shared/logging/tsconfig.json
  shared/logging/tsconfig.lib.json
  shared/logging/tsconfig.spec.json
  shared/project.json
  shared/src/lib/logging.ts
  tsconfig.base.json
Labels: documentation, enhancement

#20 WAR-83 | Created basic project structure
  apps/frontend/src/components/auth/authComponent.ts
  apps/frontend/src/components/warehouse/warehouseComponent.ts
  apps/frontend/src/pages/auth/LoginPage.ts
  apps/frontend/src/pages/warehouse/IndexPage.ts
Labels: enhancement

#23 WAR-43 Integrated warehouse service to nginx
  services/backend/nginx.default.conf
Labels: enhancement

#27 WAR-116 Connected frontend and nginx
  apps/auth/Dockerfile
  apps/frontend/Dockerfile
  apps/stock/Dockerfile
  apps/warehouse/Dockerfile
  docker-compose.yaml
  services/frontend/nginx.conf
  services/frontend/nginx.default.conf
Labels: enhancement
